export enum Scene {
  app_open = 'app_open',
  crossword = 'crossword',
  emotion_click = 'emotion_click',
  exit = 'exit',
  newsfeed = 'newsfeed',
  prayer = 'prayer',
  quiz = 'quiz',
  read_page_mark = 'read_page_mark',
  share = 'share',
  level_interstitial = 'level_interstitial',
  level_interstitial1 = 'level_interstitial1',
  level_interstitial2 = 'level_interstitial2',
  level_interstitial3 = 'level_interstitial3',
  banner = 'banner',
  gold_reward = 'gold_reward',
}
